spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
        timezone:
          default_storage: NORMALIZE
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
      driver-class-name: org.postgresql.Driver
      auto-commit: false
      connection-timeout: 3000
      max-lifetime: 50000
      pool-name: HikariCP-Writer
  flyway:
    baseline-on-migrate: true
    enabled: false

---
spring:
  config.activate.on-profile: local
  datasource:
      jdbc-url: jdbc:postgresql://localhost:5532/test
      username: user
      password: 1234
      maximum-pool-size: 10
  jpa:
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 0
    locations:
      - classpath:db/migration
      - classpath:db/data