CREATE TABLE IF NOT EXISTS "character"(
    id BIGINT not null generated by default as identity,
    created_by            varchar(255),
    created_at            timestamp     not null,
    modified_by           varchar(255),
    modified_at           timestamp     not null,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    primary key (id)
);

CREATE TABLE IF NOT EXISTS outbox_message(
    id BIGINT not null generated by default as identity,
    created_by            varchar(255),
    created_at            timestamp     not null,
    modified_by           varchar(255),
    modified_at           timestamp     not null,
    processed_at TIMESTAMP,
    character_id BIGINT not null,
    payload jsonb not null,
    primary key (id)
);
