spring:
  aop:
    proxy-target-class: true
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:example;INIT=create domain if not exists oid as blob\;create domain if not exists jsonb as json;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;
    username: sa
    password:
    initialization-mode: always
    auto-commit: false
    connection-timeout: 3000
    max-lifetime: 50000
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        connection.provider_disables_autocommit: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        timezone:
          default_storage: NORMALIZE
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
