CREATE TABLE users (
    id bigint generated by default as identity,
    created_at timestamp,
    created_by varchar(255),
    modified_at timestamp,
    modified_by varchar(255),
    name varchar(255),
    primary key (id)
);